### ISSUE TITLE
[V2] Error creating a new language in translate with msgfmt:ui preview.4

### ISSUE THREAD

**Issue by wallslide** [gadicc/meteor-messageformat#169] opened 2015-09-17 02:47 UTC
I get the error message 
```Uncaught Error: No route found named "mfTransLang"```

These are the messageformat packages I'm using:
```
msgfmt:core@2.0.0-preview.12
msgfmt:extract@2.0.0-preview.9
msgfmt:ui@2.0.0-preview.4
```

![image](https://cloud.githubusercontent.com/assets/917069/9923572/84c70afc-5d31-11e5-9b2a-463f44f3a940.png)

It happens when I click this 'go' button:
![image](https://cloud.githubusercontent.com/assets/917069/9923597/d4c0a216-5d31-11e5-868a-b8e675a30947.png)

If I downgrade to preview.3 then the problem disappears.

**Comment by Maxhodges** [comment] 2015-10-15 09:42
same problem here @gadicc  any work around?

**Comment by gadicc** [comment] 2015-10-16 13:46
hey all, thanks for your patience, can you please try `msgfmt:ui@2.0.0-preview.5` and confirm that this issue is resolved?

**Comment by DSpeichert** [comment] 2016-01-16 17:04
Can't reproduce. Seems fixed in v2.

**Closed by DSpeichert** 2016-01-16 17:04 UTC
